# Generated by Django 5.2.6 on 2025-09-06 20:06

from django.db import migrations


def forwards(apps, schema_editor):
    User = apps.get_model('accounts', 'User')
    Doctor = apps.get_model('accounts', 'Doctor')
    Patient = apps.get_model('accounts', 'Patient')
    Hospital = apps.get_model('accounts', 'Hospital')
    DoctorProfile = apps.get_model('accounts', 'DoctorProfile')
    PatientProfile = apps.get_model('accounts', 'PatientProfile')
    HospitalProfile = apps.get_model('accounts', 'HospitalProfile')

    # Move Doctor profiles
    for prof in DoctorProfile.objects.select_related('user').all():
        u = prof.user
        # Avoid duplicate if already migrated manually
        if not Doctor.objects.filter(id=u.id).exists():
            d = Doctor(id=u.id)  # keep same PK linkage for multi-table inheritance
            d.username = u.username
            d.email = u.email
            d.first_name = u.first_name
            d.last_name = u.last_name
            d.password = u.password
            d.is_active = u.is_active
            d.is_staff = u.is_staff
            d.is_superuser = u.is_superuser
            d.last_login = u.last_login
            d.date_joined = u.date_joined
            d.role = getattr(u, 'role', 'DOCTOR')
            d.specialty = prof.specialty
            d.license_number = prof.license_number
            d.years_of_experience = prof.years_of_experience
            d.clinic_address = prof.clinic_address
            d.phone = prof.phone
            d.save()

    # Move Patient profiles
    for prof in PatientProfile.objects.select_related('user').all():
        u = prof.user
        if not Patient.objects.filter(id=u.id).exists():
            p = Patient(id=u.id)
            p.username = u.username
            p.email = u.email
            p.first_name = u.first_name
            p.last_name = u.last_name
            p.password = u.password
            p.is_active = u.is_active
            p.is_staff = u.is_staff
            p.is_superuser = u.is_superuser
            p.last_login = u.last_login
            p.date_joined = u.date_joined
            p.role = getattr(u, 'role', 'PATIENT')
            p.date_of_birth = prof.date_of_birth
            p.gender = prof.gender
            p.blood_group = prof.blood_group
            p.medical_history = prof.medical_history
            p.emergency_contact_name = prof.emergency_contact_name
            p.emergency_contact_phone = prof.emergency_contact_phone
            p.save()

    # Move Hospital profiles
    for prof in HospitalProfile.objects.select_related('user').all():
        u = prof.user
        if not Hospital.objects.filter(id=u.id).exists():
            h = Hospital(id=u.id)
            h.username = u.username
            h.email = u.email
            h.first_name = u.first_name
            h.last_name = u.last_name
            h.password = u.password
            h.is_active = u.is_active
            h.is_staff = u.is_staff
            h.is_superuser = u.is_superuser
            h.last_login = u.last_login
            h.date_joined = u.date_joined
            h.role = getattr(u, 'role', 'HOSPITAL')
            h.hospital_name = prof.hospital_name
            h.registration_number = prof.registration_number
            h.address = prof.address
            h.contact_phone = prof.contact_phone
            h.bed_capacity = prof.bed_capacity
            h.save()


def backwards(apps, schema_editor):
    # We won’t implement reverse data migration for now
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_doctor_hospital_patient'),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]
