# Generated by Django 5.2.6 on 2025-09-06 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_move_profiles_to_subclasses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospitalprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='patientprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='DoctorProfile',
        ),
        migrations.DeleteModel(
            name='HospitalProfile',
        ),
        migrations.DeleteModel(
            name='PatientProfile',
        ),
    ]
